version: '3.8'

services:
  backend:
    build: ./backend/
    ports: 
      - "8080:8080"
    expose:
      - 8080
    volumes:
      - ./backend:/usr/src/app
    links:
      - db
    environment:
      DATABASE_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db/${POSTGRES_DB}"
      SMITE_DEV_KEY: "${SMITE_DEV_KEY}"
      SMITE_DEV_ID: "${SMITE_DEV_ID}"
    logging:
      driver: local
    # diesel infer_schema macro gives warnings with this flag.
    # environment:
    #   - CARGO_INCREMENTAL=1
    command: bash -c "bash ./wait-for-it.sh db:5432 -q -- diesel setup && cargo watch -x run"

  db:
    image: "postgres"
    ports: 
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"

# cargo will try to redownload packages @ docker-compose up so store them here.
volumes:
  db-data: {}
