version: '3.8'

services:

  backend:
    build: ./backend/
    container_name: smite-analyzer-api
    image: smite-analyzer-api:local
    ports: 
      - "8030:8080"
    env_file:
      - .env
    volumes:
      - ./backend:/usr/src/app
    links:
      - db
    logging:
      driver: local
    command: bash -c "bash ./wait-for-it.sh db:5432 -q -- diesel setup && cargo watch -x run"
    networks:
      - backend

  db:
    image: postgres
    container_name: postgres-db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=analyzer
    ports: 
      - "5432:5432"
    volumes: 
      - db-data:/var/lib/postgresql/data
    networks:
      - backend

  frontend:
    image: smite-analyzer-frontend
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: smite-analyzer-frontend
    volumes: 
      - ./frontend/src:/app/src
    command: npm run dev:watch
    ports: 
      - "3000:8080"
    networks:
      - backend
    env_file:
      - .env

volumes:
  db-data: {}

networks:
  backend:
    name: backend