version: '3.8'
services:

  backend:
    image: smite-analyzer:dev
    build:
      context: .
      dockerfile: compose/Dockerfile
    container_name: smite-analyzer-api
    env_file:
      - .env
    ports: 
      - "8100:3030"
    command: ["/app/target/release/smite-api"]
    
  frontend:
    image: smite-analyzer-front:dev
    build:
      context: .
      dockerfile: compose/Dockerfile-front
    container_name: smite-analyzer-frontend
    command: ["npm", "run", "serve"]
    ports: 
      - "3000:8080"
    depends_on:
      - backend